// ADMIN CONSTANTS

export const SET_USER = 'SET_USER';
export const SET_PHOTO = 'SET_PHOTO';

// CHAT CONSTANTS

export const UPDATE_CHAT_INPUT = 'UPDATE_CHAT_INPUT';
export const SEND_MESSAGE = 'SEND_MESSAGE';

// FEED CONSTANTS

export const UPDATE_FEED = 'UPDATE_FEED';

// FILTER CONSTANTS

export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';

// LAYOUT CONSTANTS

export const OPEN_POST_ISEXPANDED = 'OPEN_POST_ISEXPANDED';
export const CLOSE_POST_ISEXPANDED = 'CLOSE_POST_ISEXPANDED';
export const INVERT_SORT_ISEXPANDED = 'INVERT_SORT_ISEXPANDED';
export const OPEN_CHAT_ISEXPANDED = 'OPEN_CHAT_ISEXPANDED';
export const CLOSE_CHAT_ISEXPANDED = 'CLOSE_CHAT_ISEXPANDED';
export const CLOSE_CHAT_RENEGOTIATION_ISEXPANDED = 'CLOSE_CHAT_RENEGOTIATION_ISEXPANDED';
export const INVERT_CHAT_RENEGOTIATION_ISEXPANDED = 'INVERT_CHAT_RENEGOTIATION_ISEXPANDED';
export const OPEN_NOTIFICATION_BOX_ISOPEN = 'OPEN_NOTIFICATION_BOX_ISOPEN';
export const CLOSE_NOTIFICATION_BOX_ISOPEN = 'CLOSE_NOTIFICATION_BOX_ISOPEN';
export const INVERT_NOTIFICATION_BOX_ISOPEN = 'INVERT_NOTIFICATION_BOX_ISOPEN';
export const OPEN_PROFILE_DROPDOWN_ISOPEN = 'OPEN_PROFILE_DROPDOWN_ISOPEN';
export const CLOSE_PROFILE_DROPDOWN_ISOPEN = 'CLOSE_PROFILE_DROPDOWN_ISOPEN';
export const INVERT_PROFILE_DROPDOWN_ISOPEN = 'INVERT_PROFILE_DROPDOWN_ISOPEN';

// MODAL CONSTANTS

export const OPEN_DETAILS_MODAL_ISEXPANDED = 'OPEN_DETAILS_MODAL_ISEXPANDED';
export const CLOSE_DETAILS_MODAL_ISEXPANDED = 'CLOSE_DETAILS_MODAL_ISEXPANDED';
export const OPEN_ACCEPT_MODAL_ISEXPANDED = 'OPEN_ACCEPT_MODAL_ISEXPANDED';
export const CLOSE_ACCEPT_MODAL_ISEXPANDED = 'CLOSE_ACCEPT_MODAL_ISEXPANDED';
export const CLOSE_SETTINGS_PAYMENT_MODAL_ISEXPANDED = 'CLOSE_SETTINGS_PAYMENT_MODAL_ISEXPANDED';
export const OPEN_SETTINGS_PAYMENT_MODAL_ISEXPANDED = 'OPEN_SETTINGS_PAYMENT_MODAL_ISEXPANDED';
export const SET_MODAL_WANT_ID = 'SET_MODAL_WANT_ID';
export const SET_DETAILS_MODAL_TYPE = 'SET_DETAILS_MODAL_TYPE';

// SETTINGS CONSTANTS

export const CHANGE_SELECTED_PREFERENCE = 'CHANGE_SELECTED_PREFERENCE';