// ADMIN CONSTANTS

export const SET_USER = 'SET_USER';
export const SET_PHOTO = 'SET_PHOTO';

// FEED CONSTANTS

export const UPDATE_FEED = 'UPDATE_FEED';
export const ADD_WANTS = 'ADD_WANTS';
export const SET_NEXT_PAGE_URL = 'SET_NEXT_PAGE_URL';
export const SET_HAS_MORE_WANTS = 'SET_HAS_MORE_WANTS';

// FILTER CONSTANTS

export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const STORE_CATEGORIES = 'STORE_CATEGORIES';
export const UPDATE_CHOSEN_FILTERS = 'UPDATE_CHOSEN_FILTERS';

// LAYOUT CONSTANTS

export const OPEN_POST_ISEXPANDED = 'OPEN_POST_ISEXPANDED';
export const CLOSE_POST_ISEXPANDED = 'CLOSE_POST_ISEXPANDED';
export const INVERT_SORT_ISEXPANDED = 'INVERT_SORT_ISEXPANDED';

// MODAL CONSTANTS

export const CLOSE_SETTINGS_PAYMENT_MODAL_ISEXPANDED = 'CLOSE_SETTINGS_PAYMENT_MODAL_ISEXPANDED';
export const OPEN_SETTINGS_PAYMENT_MODAL_ISEXPANDED = 'OPEN_SETTINGS_PAYMENT_MODAL_ISEXPANDED';

// SETTINGS CONSTANTS

export const CHANGE_SELECTED_PREFERENCE = 'CHANGE_SELECTED_PREFERENCE';